variable "vpc-cidr" {}
variable "keypair-name" {}
variable "az1" {}
variable "az2" {}
variable "public1-cidr" {}
variable "public2-cidr" {}
variable "private1-cidr" {}
variable "private2-cidr" {}
variable "public-rt-cidr" {}
variable "tag-vpc" {}
variable "tag-pub-subnet1" {}
variable "tag-pub-subnet2" {}
variable "tag-prt-subnet1" {}
variable "tag-prt-subnet2" {}
variable "tag-igw" {}
variable "tag-nat" {}
variable "tag-public-rt" {}
variable "tag-private-rt" {}
variable "tag-bastion-ansible-sg" {}
variable "tag-docker-sg" {}
variable "tag-jenkins-sg" {}
variable "tag-nexus-sg" {}
variable "tag-sonarqube-sg" {}
variable "tag-mysql-sg" {}